### ISSUE TITLE
stxx variable is not defined

### ISSUE THREAD

**Issue by bumerok91** [ChartIQ/Charting-Library---Angular-1.5-Seed-Project#3]
![](https://w3tls.net/sQHR_606d9b46e4e76f3b57a20342bfa32eb87.png)

**Comment by NachoMoment** [comment]
Hi, @bumerok91. Could you please include the steps to reproduce this error?

**Comment by bumerok91** [comment]
Hello. When I tried to call a method `stxx.changeVectorType('line');` I've found out that `stxx` doesn't exist in the global scope (window).

**Comment by NachoMoment** [comment]
That is actually a known bug that has been patched so upgrading your library to version 3.0.3 or above should fix this for you.

**Comment by bumerok91** [comment]
Thanks, it works.
